
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  # categories: /categories
  search: /search
  about: /about
  rss: /atom.xml

# Miscelaneous
favicon: /logo.png

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true
#footer
index_page: https://xifanu.github.io
main_site: https://xifanu.github.io
github: https://github.com/xifanu

search:
  path: search.xml
  field: post
  content: true

#RSS feed https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content_limit: 140

sitemap:
    path: sitemap.xml

# disqus_shortname: XXX
# baidu_analytics: xxx


# # 1、Valine[一款快速、简洁且高效的无后端评论系统](https://github.com/xCss/Valine)
# # 启用Valine必须先创建leancloud应用， 获取 id|key 填入即可
# leancloud:  
#   enable: true
#   app_id: 1Nkh6N4UJhwPyNfgDqhR3cUA-gzGzoHsz
#   app_key: Spm1BsTgetPLm3s6bxgqaW0E
# # Valine配置
# valine:
#   enable: true # 是否启用
#   avatar: mp # 头像样式(https://valine.js.org/avatar.html)
#   placeholder: 给我的文章加点评论吧~ # placeholder
